### ISSUE TITLE
Problema filtrado 'small nuclear'

### ISSUE THREAD

**Issue by MarcRubFer** [MarcRubFer/decont#1]
Estoy intentando filtrar la lista de descontaminantes utilizando la opción de $4 del script download.
En un primer momento había desarrollado la siguiente línea, pensando en que el formato sería también .fastq:

_sed -e "/$4/,+3{d}"  $2/$filename_uncompress > $2/filtered/$filename_uncompress-filter_by_$4_

Pero ahora he visto que el formato de la contaminant list es diferente y no me vale esta parte del script porque donde pongo el range para el comando sed no es fijo en este caso. He probado lo siguiente lo siguiente:

_sed -n '/nuclear/,/^>/'{d} res/contaminants.fasta_ 

Pero el resultado que me devuelve incluye la siguiente línea del index fasta. Ejemplo;

_>URS000008D928_10090_ Mus musculus U3B small nuclear RNA 2 (Rnu3b2), small nuclear RNA.
AAGACUAUACUUUCAGGGAUCAUUUCUAUAGUUCGUUACUAGAGAAGUUUCUCUGACUGUGUAGAGCACCCGAAACCACG
AGGACGAGACGUAGCGUUCCCUCCUGAGCGUGAAGCCGGCUCUAGGUGCUGCUUGACUGCAGCUGCCUCCUGCCAUUGAU
GAUCGUUCUUCCCUCCUUUGGGAGGGUGAGAGGGAGGGAACGCAGUCUGAGUGGA
_>URS00000CCC1A_10090_ Mus musculus (house mouse) non-coding RNA
_>URS000060EF5E_10090_ Mus musculus U3A small nuclear RNA (Rnu3a), small nuclear RNA.
GUGAAGCCGGCUAUUAGUGCUGCAUUUUGCAACUGCUAUCUGCCAUUGAUGAUCGUUCUCAACUCUCUUGAGGGUUGAGA
GGGAGAGGACACAGUCUGAGUGGU
_>URS000045C804_10090_ Mus musculus (house mouse) U3 snRNA

Lo estoy intentando también con grep pero solo me señala la línea con el index, no la de la secuencia. Y también estoy probando con awk pero al cambiar los campos de FS y RS se me pierde el formato.

¿Alguna pista?

**Comment by nozerorma** [comment]
Me he vuelto loco con tu pregunta, no había visto que yo solo había filtrado las cabeceras y no los motivos! Después de partirme los cascos, la mejor solución que he visto es linearizar todo el documento de manera que desparezca el problema del salto de línea. Por lo que he leído, es muy importante preprocesar en este sentido los archivos FASTA antes de trabajar con ellos. 

La línea de preprocesado no la entiendo aún del todo pero es esta:
`awk '/^>/ {printf("%s%s\t",(N>0?"\n":""),$0);N++;next;} {printf("%s",$0);} END {printf("\n");}' <file>
`
Y después con un grep invertido recuperas todo lo que realmente quieres y lo rediriges al archivo filtrado o lo que quieras hacer

Te dejo la página de stacks donde lo he visto, de todas formas la mejor forma de manera local parece ser utilizar seqkit grep, que es un paquete específico.

[https://stackoverflow.com/questions/46439883/how-to-grep-the-complete-sequences-containing-a-specific-motif-in-a-fasta-file](url)

[https://bioinformatics.stackexchange.com/questions/15393/filtering-sequences-entries-by-headers-id-from-a-fasta-file-database](url)

Quedo pendiente de todas formas por si @tdido nos da otro truqui.

**Comment by tdido** [comment]
¿Vieron la sección "Filtering sequence files" del README?

**Comment by nozerorma** [comment]
Lo acabo de leer sip, no había visto lo de seqkit. Thks

**Comment by MarcRubFer** [comment]
Ciertamente encontré ese apartado después de poner el issue. Le pondré más atención al README.
Muchas gracias.
