### ISSUE TITLE
Duda instalación paquetes en el script

### ISSUE THREAD

**Issue by MarcRubFer** [MarcRubFer/decont#2]
Tengo una duda en relación a las instalación de paquetes desde el script.

En el script pipeline.sh tengo al inicio las líneas de comando para la instalación de los paquetes necesarios (seqkit, cutadapt y STAR). De momento las tengo comentadas para que no me estuvieran saltando continuamente pero no se si serían necesarias o no.

Muchas gracias.

**Comment by MarcRubFer** [comment]
Perdón, se me olvidó preguntar también si es necesario incluir en el script la línea de comando para extraer el ambiente

conda env export --from-history > envs/decont.yaml

O esto es algo que hacemos a parte nosotros y subimos al repo?

**Comment by tdido** [comment]
La idea es que la gestión de paquetes sea independiente del código, con lo cual no se incluirían comandos de instalación en los scripts y el export se hace de manera manual.

Luego quien usa tu código luego puede reconstruir tu ambiente con el comando `conda env create -f envs/decont.yaml`

**Comment by MarcRubFer** [comment]
Muchas gracias Tomás, lo sacaré del script entonces.

Cierro el issue.
